version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data  # Ensure this path matches where your SQLite DB is located
    ports:
      - "8000:8000"